// Code generated by llcppg; DO NOT EDIT.

package cjson

import "github.com/goplus/lib/c"

// Implement RFC6901 (https://tools.ietf.org/html/rfc6901) JSON Pointer spec.
//
// llgo:link (*JSON).Pointer C.cJSONUtils_GetPointer
func (self *JSON) Pointer(pointer *c.Char) *JSON {
	return self
}

// llgo:link (*JSON).PointerCaseSensitive C.cJSONUtils_GetPointerCaseSensitive
func (self *JSON) PointerCaseSensitive(pointer *c.Char) *JSON {
	return self
}

// Implement RFC6902 (https://tools.ietf.org/html/rfc6902) JSON Patch spec.
// NOTE: This modifies objects in 'from' and 'to' by sorting the elements by their key
//
// llgo:link (*JSON).GeneratePatches C.cJSONUtils_GeneratePatches
func (self *JSON) GeneratePatches(to *JSON) *JSON {
	return self
}

// llgo:link (*JSON).GeneratePatchesCaseSensitive C.cJSONUtils_GeneratePatchesCaseSensitive
func (self *JSON) GeneratePatchesCaseSensitive(to *JSON) *JSON {
	return self
}

// Utility for generating patch array entries.
//
// llgo:link (*JSON).AddPatchToArray C.cJSONUtils_AddPatchToArray
func (self *JSON) AddPatchToArray(operation *c.Char, path *c.Char, value *JSON) {
}

// Returns 0 for success.
//
// llgo:link (*JSON).ApplyPatches C.cJSONUtils_ApplyPatches
func (self *JSON) ApplyPatches(patches *JSON) c.Int {
	return 0
}

// llgo:link (*JSON).ApplyPatchesCaseSensitive C.cJSONUtils_ApplyPatchesCaseSensitive
func (self *JSON) ApplyPatchesCaseSensitive(patches *JSON) c.Int {
	return 0
}

// Implement RFC7386 (https://tools.ietf.org/html/rfc7396) JSON Merge Patch spec.
// target will be modified by patch. return value is new ptr for target.
//
// llgo:link (*JSON).MergePatch C.cJSONUtils_MergePatch
func (self *JSON) MergePatch(patch *JSON) *JSON {
	return self
}

// llgo:link (*JSON).MergePatchCaseSensitive C.cJSONUtils_MergePatchCaseSensitive
func (self *JSON) MergePatchCaseSensitive(patch *JSON) *JSON {
	return self
}

// generates a patch to move from -> to
// NOTE: This modifies objects in 'from' and 'to' by sorting the elements by their key
//
// llgo:link (*JSON).GenerateMergePatch C.cJSONUtils_GenerateMergePatch
func (self *JSON) GenerateMergePatch(to *JSON) *JSON {
	return self
}

// llgo:link (*JSON).GenerateMergePatchCaseSensitive C.cJSONUtils_GenerateMergePatchCaseSensitive
func (self *JSON) GenerateMergePatchCaseSensitive(to *JSON) *JSON {
	return self
}

// Given a root object and a target object, construct a pointer from one to the other.
//
// llgo:link (*JSON).FindPointerFromObjectTo C.cJSONUtils_FindPointerFromObjectTo
func (self *JSON) FindPointerFromObjectTo(target *JSON) *c.Char {
	return nil
}

// Sorts the members of the object into alphabetical order.
//
// llgo:link (*JSON).SortObject C.cJSONUtils_SortObject
func (self *JSON) SortObject() {
}

// llgo:link (*JSON).SortObjectCaseSensitive C.cJSONUtils_SortObjectCaseSensitive
func (self *JSON) SortObjectCaseSensitive() {
}
