// Code generated by llcppg; DO NOT EDIT.

package cjson

import (
	"github.com/goplus/lib/c"
	"unsafe"
)

const VERSION_MAJOR = 1
const VERSION_MINOR = 7
const VERSION_PATCH = 19
const Invalid = 0
const False = 1
const True = 2
const Null = 4
const Number = 8
const String = 16
const Array = 32
const Object = 64
const Raw = 128
const IsReference = 256
const StringIsConst = 512
const NESTING_LIMIT = 1000
const CIRCULAR_LIMIT = 10000

// The cJSON structure:
type JSON struct {
	Next        *JSON
	Prev        *JSON
	Child       *JSON
	Type        c.Int
	Valuestring *c.Char
	Valueint    c.Int
	Valuedouble c.Double
	String      *c.Char
}

// llgo:type C
type Hooks struct {
	MallocFn func(_llcppg_param1 c.SizeT) unsafe.Pointer
	FreeFn   func(_llcppg_param1 unsafe.Pointer)
}
type Bool = c.Int

// returns the version of cJSON as a string
//
//go:linkname Version C.cJSON_Version
func Version() *c.Char

// Supply malloc, realloc and free functions to cJSON
//
// llgo:link (*Hooks).Init C.cJSON_InitHooks
func (self *Hooks) Init() {
}

// Memory Management: the caller is always responsible to free the results from all variants of cJSON_Parse (with cJSON_Delete) and cJSON_Print (with stdlib free, cJSON_Hooks.free_fn, or cJSON_free as appropriate). The exception is cJSON_PrintPreallocated, where the caller has full responsibility of the buffer.
// Supply a block of JSON, and this returns a cJSON object you can interrogate.
//
//go:linkname Parse C.cJSON_Parse
func Parse(value *c.Char) *JSON

//go:linkname ParseWithLength C.cJSON_ParseWithLength
func ParseWithLength(value *c.Char, buffer_length c.SizeT) *JSON

// ParseWithOpts allows you to require (and check) that the JSON is null terminated, and to retrieve the pointer to the final byte parsed.
// If you supply a ptr in return_parse_end and parsing fails, then return_parse_end will contain a pointer to the error so will match cJSON_GetErrorPtr().
//
//go:linkname ParseWithOpts C.cJSON_ParseWithOpts
func ParseWithOpts(value *c.Char, return_parse_end **c.Char, require_null_terminated Bool) *JSON

//go:linkname ParseWithLengthOpts C.cJSON_ParseWithLengthOpts
func ParseWithLengthOpts(value *c.Char, buffer_length c.SizeT, return_parse_end **c.Char, require_null_terminated Bool) *JSON

// Render a cJSON entity to text for transfer/storage.
//
// llgo:link (*JSON).Print C.cJSON_Print
func (self *JSON) Print() *c.Char {
	return nil
}

// Render a cJSON entity to text for transfer/storage without any formatting.
//
// llgo:link (*JSON).PrintUnformatted C.cJSON_PrintUnformatted
func (self *JSON) PrintUnformatted() *c.Char {
	return nil
}

// Render a cJSON entity to text using a buffered strategy. prebuffer is a guess at the final size. guessing well reduces reallocation. fmt=0 gives unformatted, =1 gives formatted
//
// llgo:link (*JSON).PrintBuffered C.cJSON_PrintBuffered
func (self *JSON) PrintBuffered(prebuffer c.Int, fmt Bool) *c.Char {
	return nil
}

// Render a cJSON entity to text using a buffer already allocated in memory with given length. Returns 1 on success and 0 on failure.
// NOTE: cJSON is not always 100% accurate in estimating how much memory it will use, so to be safe allocate 5 bytes more than you actually need
//
// llgo:link (*JSON).PrintPreallocated C.cJSON_PrintPreallocated
func (self *JSON) PrintPreallocated(buffer *c.Char, length c.Int, format Bool) Bool {
	return 0
}

// Delete a cJSON entity and all subentities.
//
// llgo:link (*JSON).Delete C.cJSON_Delete
func (self *JSON) Delete() {
}

// Returns the number of items in an array (or object).
//
// llgo:link (*JSON).ArraySize C.cJSON_GetArraySize
func (self *JSON) ArraySize() c.Int {
	return 0
}

// Retrieve item number "index" from array "array". Returns NULL if unsuccessful.
//
// llgo:link (*JSON).ArrayItem C.cJSON_GetArrayItem
func (self *JSON) ArrayItem(index c.Int) *JSON {
	return self
}

// Get item "string" from object. Case insensitive.
//
// llgo:link (*JSON).ObjectItem C.cJSON_GetObjectItem
func (self *JSON) ObjectItem(string *c.Char) *JSON {
	return self
}

// llgo:link (*JSON).ObjectItemCaseSensitive C.cJSON_GetObjectItemCaseSensitive
func (self *JSON) ObjectItemCaseSensitive(string *c.Char) *JSON {
	return self
}

// llgo:link (*JSON).HasObjectItem C.cJSON_HasObjectItem
func (self *JSON) HasObjectItem(string *c.Char) Bool {
	return 0
}

// For analysing failed parses. This returns a pointer to the parse error. You'll probably need to look a few chars back to make sense of it. Defined when cJSON_Parse() returns 0. 0 when cJSON_Parse() succeeds.
//
//go:linkname GetErrorPtr C.cJSON_GetErrorPtr
func GetErrorPtr() *c.Char

// Check item type and return its value
//
// llgo:link (*JSON).StringValue C.cJSON_GetStringValue
func (self *JSON) StringValue() *c.Char {
	return nil
}

// llgo:link (*JSON).NumberValue C.cJSON_GetNumberValue
func (self *JSON) NumberValue() c.Double {
	return 0
}

// These functions check the type of an item
//
// llgo:link (*JSON).IsInvalid C.cJSON_IsInvalid
func (self *JSON) IsInvalid() Bool {
	return 0
}

// llgo:link (*JSON).IsFalse C.cJSON_IsFalse
func (self *JSON) IsFalse() Bool {
	return 0
}

// llgo:link (*JSON).IsTrue C.cJSON_IsTrue
func (self *JSON) IsTrue() Bool {
	return 0
}

// llgo:link (*JSON).IsBool C.cJSON_IsBool
func (self *JSON) IsBool() Bool {
	return 0
}

// llgo:link (*JSON).IsNull C.cJSON_IsNull
func (self *JSON) IsNull() Bool {
	return 0
}

// llgo:link (*JSON).IsNumber C.cJSON_IsNumber
func (self *JSON) IsNumber() Bool {
	return 0
}

// llgo:link (*JSON).IsString C.cJSON_IsString
func (self *JSON) IsString() Bool {
	return 0
}

// llgo:link (*JSON).IsArray C.cJSON_IsArray
func (self *JSON) IsArray() Bool {
	return 0
}

// llgo:link (*JSON).IsObject C.cJSON_IsObject
func (self *JSON) IsObject() Bool {
	return 0
}

// llgo:link (*JSON).IsRaw C.cJSON_IsRaw
func (self *JSON) IsRaw() Bool {
	return 0
}

// These calls create a cJSON item of the appropriate type.
//
//go:linkname CreateNull C.cJSON_CreateNull
func CreateNull() *JSON

//go:linkname CreateTrue C.cJSON_CreateTrue
func CreateTrue() *JSON

//go:linkname CreateFalse C.cJSON_CreateFalse
func CreateFalse() *JSON

//go:linkname CreateBool C.cJSON_CreateBool
func CreateBool(boolean Bool) *JSON

//go:linkname CreateNumber C.cJSON_CreateNumber
func CreateNumber(num c.Double) *JSON

//go:linkname CreateString C.cJSON_CreateString
func CreateString(string *c.Char) *JSON

// raw json
//
//go:linkname CreateRaw C.cJSON_CreateRaw
func CreateRaw(raw *c.Char) *JSON

//go:linkname CreateArray C.cJSON_CreateArray
func CreateArray() *JSON

//go:linkname CreateObject C.cJSON_CreateObject
func CreateObject() *JSON

// Create a string where valuestring references a string so
// it will not be freed by cJSON_Delete
//
//go:linkname CreateStringReference C.cJSON_CreateStringReference
func CreateStringReference(string *c.Char) *JSON

// Create an object/array that only references it's elements so
// they will not be freed by cJSON_Delete
//
// llgo:link (*JSON).CreateObjectReference C.cJSON_CreateObjectReference
func (self *JSON) CreateObjectReference() *JSON {
	return self
}

// llgo:link (*JSON).CreateArrayReference C.cJSON_CreateArrayReference
func (self *JSON) CreateArrayReference() *JSON {
	return self
}

// These utilities create an Array of count items.
// The parameter count cannot be greater than the number of elements in the number array, otherwise array access will be out of bounds.
//
//go:linkname CreateIntArray C.cJSON_CreateIntArray
func CreateIntArray(numbers *c.Int, count c.Int) *JSON

//go:linkname CreateFloatArray C.cJSON_CreateFloatArray
func CreateFloatArray(numbers *c.Float, count c.Int) *JSON

//go:linkname CreateDoubleArray C.cJSON_CreateDoubleArray
func CreateDoubleArray(numbers *c.Double, count c.Int) *JSON

//go:linkname CreateStringArray C.cJSON_CreateStringArray
func CreateStringArray(strings **c.Char, count c.Int) *JSON

// Append item to the specified array/object.
//
// llgo:link (*JSON).AddItemToArray C.cJSON_AddItemToArray
func (self *JSON) AddItemToArray(item *JSON) Bool {
	return 0
}

// llgo:link (*JSON).AddItemToObject C.cJSON_AddItemToObject
func (self *JSON) AddItemToObject(string *c.Char, item *JSON) Bool {
	return 0
}

// Use this when string is definitely const (i.e. a literal, or as good as), and will definitely survive the cJSON object.
// WARNING: When this function was used, make sure to always check that (item->type & cJSON_StringIsConst) is zero before
// writing to `item->string`
//
// llgo:link (*JSON).AddItemToObjectCS C.cJSON_AddItemToObjectCS
func (self *JSON) AddItemToObjectCS(string *c.Char, item *JSON) Bool {
	return 0
}

// Append reference to item to the specified array/object. Use this when you want to add an existing cJSON to a new cJSON, but don't want to corrupt your existing cJSON.
//
// llgo:link (*JSON).AddItemReferenceToArray C.cJSON_AddItemReferenceToArray
func (self *JSON) AddItemReferenceToArray(item *JSON) Bool {
	return 0
}

// llgo:link (*JSON).AddItemReferenceToObject C.cJSON_AddItemReferenceToObject
func (self *JSON) AddItemReferenceToObject(string *c.Char, item *JSON) Bool {
	return 0
}

// Remove/Detach items from Arrays/Objects.
//
// llgo:link (*JSON).DetachItemViaPointer C.cJSON_DetachItemViaPointer
func (self *JSON) DetachItemViaPointer(item *JSON) *JSON {
	return self
}

// llgo:link (*JSON).DetachItemFromArray C.cJSON_DetachItemFromArray
func (self *JSON) DetachItemFromArray(which c.Int) *JSON {
	return self
}

// llgo:link (*JSON).DeleteItemFromArray C.cJSON_DeleteItemFromArray
func (self *JSON) DeleteItemFromArray(which c.Int) {
}

// llgo:link (*JSON).DetachItemFromObject C.cJSON_DetachItemFromObject
func (self *JSON) DetachItemFromObject(string *c.Char) *JSON {
	return self
}

// llgo:link (*JSON).DetachItemFromObjectCaseSensitive C.cJSON_DetachItemFromObjectCaseSensitive
func (self *JSON) DetachItemFromObjectCaseSensitive(string *c.Char) *JSON {
	return self
}

// llgo:link (*JSON).DeleteItemFromObject C.cJSON_DeleteItemFromObject
func (self *JSON) DeleteItemFromObject(string *c.Char) {
}

// llgo:link (*JSON).DeleteItemFromObjectCaseSensitive C.cJSON_DeleteItemFromObjectCaseSensitive
func (self *JSON) DeleteItemFromObjectCaseSensitive(string *c.Char) {
}

// Update array items.
//
// llgo:link (*JSON).InsertItemInArray C.cJSON_InsertItemInArray
func (self *JSON) InsertItemInArray(which c.Int, newitem *JSON) Bool {
	return 0
}

// llgo:link (*JSON).ReplaceItemViaPointer C.cJSON_ReplaceItemViaPointer
func (self *JSON) ReplaceItemViaPointer(item *JSON, replacement *JSON) Bool {
	return 0
}

// llgo:link (*JSON).ReplaceItemInArray C.cJSON_ReplaceItemInArray
func (self *JSON) ReplaceItemInArray(which c.Int, newitem *JSON) Bool {
	return 0
}

// llgo:link (*JSON).ReplaceItemInObject C.cJSON_ReplaceItemInObject
func (self *JSON) ReplaceItemInObject(string *c.Char, newitem *JSON) Bool {
	return 0
}

// llgo:link (*JSON).ReplaceItemInObjectCaseSensitive C.cJSON_ReplaceItemInObjectCaseSensitive
func (self *JSON) ReplaceItemInObjectCaseSensitive(string *c.Char, newitem *JSON) Bool {
	return 0
}

// Duplicate a cJSON item
//
// llgo:link (*JSON).Duplicate C.cJSON_Duplicate
func (self *JSON) Duplicate(recurse Bool) *JSON {
	return self
}

// Duplicate will create a new, identical cJSON item to the one you pass, in new memory that will
// need to be released. With recurse!=0, it will duplicate any children connected to the item.
// The item->next and ->prev pointers are always zero on return from Duplicate.
// Recursively compare two cJSON items for equality. If either a or b is NULL or invalid, they will be considered unequal.
// case_sensitive determines if object keys are treated case sensitive (1) or case insensitive (0)
//
// llgo:link (*JSON).Compare C.cJSON_Compare
func (self *JSON) Compare(b *JSON, case_sensitive Bool) Bool {
	return 0
}

// Minify a strings, remove blank characters(such as ' ', '\t', '\r', '\n') from strings.
// The input pointer json cannot point to a read-only address area, such as a string constant,
// but should point to a readable and writable address area.
//
//go:linkname Minify C.cJSON_Minify
func Minify(json *c.Char)

// Helper functions for creating and adding items to an object at the same time.
// They return the added item or NULL on failure.
//
// llgo:link (*JSON).AddNullToObject C.cJSON_AddNullToObject
func (self *JSON) AddNullToObject(name *c.Char) *JSON {
	return self
}

// llgo:link (*JSON).AddTrueToObject C.cJSON_AddTrueToObject
func (self *JSON) AddTrueToObject(name *c.Char) *JSON {
	return self
}

// llgo:link (*JSON).AddFalseToObject C.cJSON_AddFalseToObject
func (self *JSON) AddFalseToObject(name *c.Char) *JSON {
	return self
}

// llgo:link (*JSON).AddBoolToObject C.cJSON_AddBoolToObject
func (self *JSON) AddBoolToObject(name *c.Char, boolean Bool) *JSON {
	return self
}

// llgo:link (*JSON).AddNumberToObject C.cJSON_AddNumberToObject
func (self *JSON) AddNumberToObject(name *c.Char, number c.Double) *JSON {
	return self
}

// llgo:link (*JSON).AddStringToObject C.cJSON_AddStringToObject
func (self *JSON) AddStringToObject(name *c.Char, string *c.Char) *JSON {
	return self
}

// llgo:link (*JSON).AddRawToObject C.cJSON_AddRawToObject
func (self *JSON) AddRawToObject(name *c.Char, raw *c.Char) *JSON {
	return self
}

// llgo:link (*JSON).AddObjectToObject C.cJSON_AddObjectToObject
func (self *JSON) AddObjectToObject(name *c.Char) *JSON {
	return self
}

// llgo:link (*JSON).AddArrayToObject C.cJSON_AddArrayToObject
func (self *JSON) AddArrayToObject(name *c.Char) *JSON {
	return self
}

// helper for the cJSON_SetNumberValue macro
//
// llgo:link (*JSON).SetNumberHelper C.cJSON_SetNumberHelper
func (self *JSON) SetNumberHelper(number c.Double) c.Double {
	return 0
}

// Change the valuestring of a cJSON_String object, only takes effect when type of object is cJSON_String
//
// llgo:link (*JSON).SetValuestring C.cJSON_SetValuestring
func (self *JSON) SetValuestring(valuestring *c.Char) *c.Char {
	return nil
}

// malloc/free objects using the malloc/free functions that have been set with cJSON_InitHooks
//
//go:linkname Malloc C.cJSON_malloc
func Malloc(size c.SizeT) unsafe.Pointer

//go:linkname Free C.cJSON_free
func Free(object unsafe.Pointer)
